# Generated by Django 6.0.5 on 2026-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_saldo_pendiente_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
