# Generated by Django 6.0.5 on 2026-05-06 21:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_ganancia_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
