# Generated by Django 6.0.5 on 2026-05-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_prestamo_ganancia_alter_prestamo_interes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cuota',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='ganancia',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='total',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado_pagado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='interes_porcentaje',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Interés %'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_cuota',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='diario', max_length=15),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto que recibe Papá (S/) '),
        ),
        migrations.AlterField(
            model_name='pago',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='prestamos.prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Prestado (S/) '),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
