services:
  - type: web
    name: sistema-prestamos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # O la versión que uses
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings